name: Build
on:
  pull_request:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    env:
      PKGFORGE_STATEFILE: /tmp/pkgforge
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: make
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      run: make release
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Post to a Slack channel
      if: ${{ failure() }}
      uses: slackapi/slack-github-action@v1.18.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "text": "*${{ github.repository }}*\nBuild failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*${{ github.repository }}*\nBuild failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              }
            ]
          }
